[package]
authors = ["Solana Maintainers <maintainers@solana.foundation>"]
edition = "2018"
name = "solana-local-cluster"
description = "Blockchain, Rebuilt for Scale"
version = "1.5.0"
repository = "https://github.com/solana-labs/solana"
license = "Apache-2.0"
homepage = "https://solana.com/"

[dependencies]
itertools = "0.9.0"
gag = "0.1.10"
fs_extra = "1.1.0"
log = "0.4.8"
rand = "0.7.0"
solana-config-program = { path = "../programs/config", version = "1.5.0" }
solana-core = { path = "../core", version = "1.5.0" }
solana-client = { path = "../client", version = "1.5.0" }
solana-download-utils = { path = "../download-utils", version = "1.5.0" }
solana-faucet = { path = "../faucet", version = "1.5.0" }
solana-exchange-program = { path = "../programs/exchange", version = "1.5.0" }
solana-ledger = { path = "../ledger", version = "1.5.0" }
solana-logger = { path = "../logger", version = "1.5.0" }
solana-runtime = { path = "../runtime", version = "1.5.0" }
solana-sdk = { path = "../sdk", version = "1.5.0" }
solana-stake-program = { path = "../programs/stake", version = "1.5.0" }
solana-vest-program = { path = "../programs/vest", version = "1.5.0" }
solana-vote-program = { path = "../programs/vote", version = "1.5.0" }
tempfile = "3.1.0"
solana-rayon-threadlimit = { path = "../rayon-threadlimit", version = "1.5.0" }
serde_derive = "1.0.117"
lazy_static = "1.4.0"

toml-config = { path = "../toml-config" }

[dev-dependencies]
assert_matches = "1.3.0"
serial_test = "0.4.0"
serial_test_derive = "0.4.0"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]
