[workspace]
members = [
    "bench-exchange",
    "bench-streamer",
    "bench-tps",
    "accounts-bench",
    "banking-bench",
    "banks-client",
    "banks-interface",
    "banks-server",
    "clap-utils",
    "cli-config",
    "cli-output",
    "client",
    "core",
    "dos",
    "download-utils",
    "faucet",
    "frozen-abi",
    "perf",
    "validator",
    "genesis",
    "gossip",
    "install",
    "keygen",
    "ledger",
    "ledger-tool",
    "local-cluster",
    "logger",
    "log-analyzer",
    "merkle-tree",
    "stake-o-matic",
    "storage-bigtable",
    "storage-proto",
    "streamer",
    "measure",
    "metrics",
    "net-shaper",
    "notifier",
    "poh-bench",
    "programs/secp256k1",
    "programs/bpf_loader",
    "programs/budget",
    "programs/config",
    "programs/exchange",
    "programs/failure",
    "programs/noop",
    "programs/ownable",
    "programs/stake",
    "programs/vest",
    "programs/vote",
    "remote-wallet",
    "ramp-tps",
    "runtime",
    "sdk",
    "sdk/cargo-build-bpf",
    "scripts",
    "stake-accounts",
    "stake-monitor",
    "sys-tuner",
    "tokens",
    "transaction-status",
    "account-decoder",
    "upload-perf",
    "net-utils",
    "version",
    "vote-signer",
    "cli",
    "rayon-threadlimit",
    "watchtower",
    "toml-config",
]

exclude = [
    "programs/bpf",
]
