[solana-gossip]
CRDS_GOSSIP_NUM_ACTIVE = 30 #usize
CRDS_GOSSIP_PUSH_FANOUT = 6 #usize
CRDS_GOSSIP_PUSH_MSG_TIMEOUT_MS = 30000 #u64
CRDS_GOSSIP_PRUNE_MSG_TIMEOUT_MS = 500 #u64
CRDS_GOSSIP_PRUNE_STAKE_THRESHOLD_PCT = 0.15 #f64
CRDS_GOSSIP_PRUNE_MIN_INGRESS_NODES = 3 # usize

[solana-core]
FORWARD_TRANSACTIONS_TO_LEADER_AT_SLOT_OFFSET = 2 #u64
NUM_THREADS = 4 #u32

NUM_BAD_SLOTS  = 10 #u64
SLOT_TO_RESOLVE = 32 #u64

DATA_PLANE_FANOUT = 200 #usize
GOSSIP_SLEEP_MILLIS = 100 #u64

MAX_CRDS_OBJECT_SIZE = 928 #usize
MAX_SNAPSHOT_HASHES = 16 #usize
VOTE_THRESHOLD_DEPTH = 8 #usize

CRDS_GOSSIP_PULL_CRDS_TIMEOUT_MS = 15000 #u64
CRDS_GOSSIP_PULL_MSG_TIMEOUT_MS = 60000 #u64

DEFAULT_MAX_LEDGER_SHREDS = 200_000_000 #u64
DEFAULT_MIN_MAX_LEDGER_SHREDS = 50_000_000 #u64
DEFAULT_PURGE_SLOT_INTERVAL = 512 #u64

GRACE_TICKS_FACTOR = 2 # u64
MAX_GRACE_SLOTS = 2 # u64

SUPERMINORITY_THRESHOLD = 1f64 / 3f64 #f64

[solana-runtime]
DEFAULT_NUM_THREADS = 8 #u32
DEFAULT_NUM_DIRS = 4 #u32

ITER_BATCH_SIZE = 1000 #usize
MAX_LEADER_SCHEDULE_STAKES = 5 #Epoch
VOTE_THRESHOLD_SIZE = 2f64 / 3f64 #f64

[solana-ledger]
MAX_COMPLETED_SLOTS_IN_CHANNEL = 100_000 #usize
MAX_TURBINE_PROPAGATION_IN_MS = 100 #u64

MAX_DATA_SHREDS_PER_SLOT = 32_768 #usize

SIGN_SHRED_GPU_MIN  = 256 #usize