[solana-gossip]
CRDS_GOSSIP_NUM_ACTIVE = 30 #usize
CRDS_GOSSIP_PUSH_FANOUT = 6 #usize
CRDS_GOSSIP_PUSH_MSG_TIMEOUT_MS = 30000 #u64
CRDS_GOSSIP_PRUNE_MSG_TIMEOUT_MS = 500 #u64
CRDS_GOSSIP_PRUNE_STAKE_THRESHOLD_PCT = 0.15 #f64
CRDS_GOSSIP_PRUNE_MIN_INGRESS_NODES = 3 #usize
