[package]
name = "solana-program"
version = "1.5.0"
description = "Solana Program"
authors = ["Solana Maintainers <maintainers@solana.foundation>"]
repository = "https://github.com/solana-labs/solana"
homepage = "https://solana.com/"
license = "Apache-2.0"
edition = "2018"

[dependencies]
bincode = "1.3.1"
bs58 = "0.3.1"
bv = { version = "0.11.1", features = ["serde"] }
hex = "0.4.2"
itertools =  "0.9.0"
lazy_static = "1.4.0"
log = "0.4.8"
num-derive = "0.3"
num-traits = "0.2"
rustversion = "1.0.3"
serde = "1.0.112"
serde_bytes = "0.11"
serde_derive = "1.0.103"
sha2 = "0.8.2"
solana-frozen-abi = { path = "../../frozen-abi", version = "1.5.0" }
solana-frozen-abi-macro = { path = "../../frozen-abi/macro", version = "1.5.0" }
solana-sdk-macro = { path = "../macro", version = "1.5.0" }
thiserror = "1.0"

toml-config = { path = "../../toml-config" }

[target.'cfg(not(target_arch = "bpf"))'.dependencies]
curve25519-dalek = { version = "2.1.0" }
rand = "0.7.0"
solana-logger = { path = "../../logger", version = "1.5.0" }

[dev-dependencies]
assert_matches = "1.3.0"
bincode = "1.3.1"
serde_json = "1.0.56"

[build-dependencies]
rustc_version = "0.2"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]
