[package]
authors = ["Solana Maintainers <maintainers@solana.foundation>"]
edition = "2018"
name = "solana-validator"
description = "Blockchain, Rebuilt for Scale"
version = "1.5.0"
repository = "https://github.com/solana-labs/solana"
license = "Apache-2.0"
homepage = "https://solana.com/"

[dependencies]
clap = "2.33.1"
chrono = { version = "0.4.11", features = ["serde"] }
console = "0.15.0"
log = "0.4.8"
rand = "0.7.0"
serde_json = "1.0.56"
solana-clap-utils = { path = "../clap-utils", version = "1.5.0" }
solana-client = { path = "../client", version = "1.5.0" }
solana-core = { path = "../core", version = "1.5.0" }
solana-download-utils = { path = "../download-utils", version = "1.5.0" }
solana-faucet = { path = "../faucet", version = "1.5.0" }
solana-ledger = { path = "../ledger", version = "1.5.0" }
solana-logger = { path = "../logger", version = "1.5.0" }
solana-perf = { path = "../perf", version = "1.5.0" }
solana-metrics = { path = "../metrics", version = "1.5.0" }
solana-net-utils = { path = "../net-utils", version = "1.5.0" }
solana-runtime = { path = "../runtime", version = "1.5.0" }
solana-sdk = { path = "../sdk", version = "1.5.0" }
solana-version = { path = "../version", version = "1.5.0" }
solana-vote-program = { path = "../programs/vote", version = "1.5.0" }
solana-vote-signer = { path = "../vote-signer", version = "1.5.0" }

[target."cfg(unix)".dependencies]
libc = "0.2.72"
signal-hook = "0.1.15"

#[[bin]]
#name = "solana-validator"
#path = "src/main.rs"
#
#[lib]
#name = "solana_validator"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]
