[package]
name = "solana-runtime"
version = "1.5.0"
description = "Solana runtime"
authors = ["Solana Maintainers <maintainers@solana.foundation>"]
repository = "https://github.com/solana-labs/solana"
license = "Apache-2.0"
homepage = "https://solana.com/"
edition = "2018"

[dependencies]
bincode = "1.3.1"
blake3 = "0.3.6"
bv = { version = "0.11.1", features = ["serde"] }
byteorder = "1.3.4"
bzip2 = "0.3.3"
dashmap = "3.11.10"
crossbeam-channel = "0.4"
dir-diff = "0.3.2"
flate2 = "1.0.14"
fnv = "1.0.7"
fs_extra = "1.1.0"
itertools = "0.9.0"
lazy_static = "1.4.0"
libc = "0.2.72"
libloading = "0.6.2"
log = "0.4.8"
memmap = "0.7.0"
num-derive = { version = "0.3" }
num-traits = { version = "0.2" }
num_cpus = "1.13.0"
ouroboros = "0.4.0"
rand = "0.7.0"
rayon = "1.4.1"
regex = "1.3.9"
serde = { version = "1.0.112", features = ["rc"] }
serde_derive = "1.0.103"
solana-config-program = { path = "../programs/config", version = "1.5.0" }
solana-frozen-abi = { path = "../frozen-abi", version = "1.5.0" }
solana-frozen-abi-macro = { path = "../frozen-abi/macro", version = "1.5.0" }
solana-logger = { path = "../logger", version = "1.5.0" }
solana-measure = { path = "../measure", version = "1.5.0" }
solana-metrics = { path = "../metrics", version = "1.5.0" }
solana-rayon-threadlimit = { path = "../rayon-threadlimit", version = "1.5.0" }
solana-sdk = { path = "../sdk", version = "1.5.0" }
solana-stake-program = { path = "../programs/stake", version = "1.5.0" }
solana-vote-program = { path = "../programs/vote", version = "1.5.0" }
solana-secp256k1-program = { path = "../programs/secp256k1", version = "1.5.0" }
symlink = "0.1.0"
tar = "0.4.28"
tempfile = "3.3.0"
thiserror = "1.0"
zstd = "0.5.1"

toml-config = { path = "../toml-config" }

[lib]
crate-type = ["lib"]
name = "solana_runtime"

[dev-dependencies]
assert_matches = "1.3.0"
solana-noop-program = { path = "../programs/noop", version = "1.5.0" }

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[build-dependencies]
rustc_version = "0.2"
