[package]
name = "solana-perf"
version = "1.5.0"
description = "Solana Performance APIs"
authors = ["Solana Maintainers <maintainers@solana.foundation>"]
repository = "https://github.com/solana-labs/solana"
license = "Apache-2.0"
homepage = "https://solana.com/"
edition = "2018"

[dependencies]
rand = "0.7.0"
dlopen = "0.1.8"
bincode = "1.3.1"
rayon = "1.4.0"
serde = "1.0.112"
dlopen_derive = "0.1.4"
lazy_static = "1.4.0"
log = "0.4.8"
solana-sdk = { path = "../sdk", version = "1.5.0" }
solana-rayon-threadlimit = { path = "../rayon-threadlimit", version = "1.5.0" }
solana-budget-program = { path = "../programs/budget", version = "1.5.0" }
solana-logger = { path = "../logger", version = "1.5.0" }
solana-metrics = { path = "../metrics", version = "1.5.0" }
curve25519-dalek = { version = "2" }

toml-config = { path = "../toml-config" }
serde_derive = "1.0.117"

[lib]
name = "solana_perf"

[dev-dependencies]
matches = "0.1.6"

[[bench]]
name = "sigverify"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]
