[package]
authors = ["Solana Maintainers <maintainers@solana.foundation>"]
edition = "2018"
name = "solana-install"
description = "The solana cluster software installer"
version = "1.5.0"
repository = "https://github.com/solana-labs/solana"
license = "Apache-2.0"
homepage = "https://solana.com/"

[dependencies]
atty = "0.2.11"
bincode = "1.3.1"
bzip2 = "0.3.3"
chrono = { version = "0.4.11", features = ["serde"] }
clap = { version = "2.33.1" }
console = "0.11.3"
ctrlc = { version = "3.1.5", features = ["termination"] }
dirs = "2.0.2"
indicatif = "0.15.0"
lazy_static = "1.4.0"
nix = "0.17.0"
reqwest = { version = "0.10.8", default-features = false, features = ["blocking", "rustls-tls", "json"] }
serde = "1.0.112"
serde_derive = "1.0.103"
serde_yaml = "0.8.13"
solana-clap-utils = { path = "../clap-utils", version = "1.5.0" }
solana-client = { path = "../client", version = "1.5.0" }
solana-config-program = { path = "../programs/config", version = "1.5.0" }
solana-logger = { path = "../logger", version = "1.5.0" }
solana-sdk = { path = "../sdk", version = "1.5.0" }
solana-version = { path = "../version", version = "1.5.0" }
semver = "0.9.0"
tar = "0.4.28"
tempfile = "3.2.0"
url = "2.1.1"

[target."cfg(windows)".dependencies]
winapi = "0.3.8"
winreg = "0.7"

[[bin]]
name = "solana-install"
path = "src/main-install.rs"

[[bin]]
name = "solana-install-init"
path = "src/main-install-init.rs"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]
