[package]
name = "toml-config"
version = "0.0.0"
authors = ["hrls <viktor.kharitonovich@gmail.com>"]
edition = "2018"

[dependencies]
toml = "0.5.7"
lazy_static = "1.4.0"
serde = "1.0.117"
serde_derive = "1.0.117"
thiserror = "1.0.22"
